export type TUserAchievement = {
    achievementId: number,
    code: string,
    coins: number,
    completed: boolean,
    description: string,
    eventReplays: number,
    experience: number,
    id: number,
    name: string,
    received: boolean,
    replays: number,
    sort: number,
    sectionId: number,
}