export type TPopupData = {
    title?:string,
    noTitle?:boolean,
    subtitle?:string,
    noClose?:boolean,
    noCloseButton?:boolean,
    noPaddings?:boolean,
    noBackground?:boolean,
    fullHeight?:boolean,
    pink?:boolean,
    small?:boolean,
    class?:string,
    backgroundBlur?: boolean,
    backdropBlur?:boolean,
    darkBg?:boolean,
    modal?:boolean,
} | {[key:string]:any}
